# Generated by Django 4.2.5 on 2023-09-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
