# Generated by Django 4.2.5 on 2023-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacters', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
            ],
        ),
    ]
