# Generated by Django 4.2.5 on 2023-09-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacters', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
